version: "3"
services:
  authors:
    image: estoyanov/bff-authors-service:1.0
    volumes:
      - ./logs:/logs
    container_name: bff-authors-service
    ports:
      - 8081:8081
    networks:
      - mynet
  books:
    image: estoyanov/bff-books-service:1.0
    volumes:
      - ./logs:/logs
    container_name: bff-books-service
    ports:
      - 8082:8082
    networks:
      - mynet
  web-sockets:
    image: estoyanov/bff-web-sockets-service:1.0
    container_name: bff-web-sockets-service
    ports:
      - 8083:8083
    networks:
      - mynet
  redis:
    image: redis:latest
    container_name: bff-redis
    ports:
      - 16379:6379
    networks:
      - mynet

  bff-frontend:
    image: estoyanov/bff-frontend:1.0
    container_name: bff-frontend-service
    ports:
       - 8084:8084
    networks:
        - mynet

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
       - 9411:9411
    networks:
        - mynet


  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.2.0"
    container_name: bff-elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
      image: "docker.elastic.co/kibana/kibana:7.2.0"
      container_name: bff-kibana
      ports:
          - "5601:5601"

  filebeat:
      image: "docker.elastic.co/beats/filebeat:7.2.0"
      container_name: bff-filebeat
      user: root
      volumes:
          - "./filebeat/filebeat.yaml:/usr/share/filebeat/filebeat.yml:ro"
          - /var/lib/docker:/var/lib/docker:ro
          - /var/run/docker.sock:/var/run/docker.sock
          - "./logs:/usr/share/filebeat/logs"
      command: ["--strict.perms=false"]

volumes:
    elasticsearch_data:

networks:
  mynet:
